### ISSUE TITLE
Create Rooms on Telegram

### ISSUE THREAD

**Issue by yncyrydybyl** [polychatproject/polychat-appservice#3]
Create a Sub room:
* Invite @telegrambot:polychat.de into the room. (i hope it joins automatically)
* within the subroom activate the bridge
create [type] - Create a Telegram chat of the given type for the current Matrix room. The type is either group, supergroup or channel (defaults to supergroup).
* and get the invitelinks for the remote room and store it. That will be used for the next user to join the remote-room
invite-link [--uses=<amount>] [--expire=<time delta, e.g. 1d>] [--request-needed] -- [title] - Get a Telegram invite link to the current chat.

**Comment by jaller94** [comment]
Implemented and good enough for now :tm:
