### ISSUE TITLE
Create Versioning

### ISSUE THREAD

**Issue by nadineminagawa** [polychatproject/polychat-appservice#34]
As a user reporting a bug, I want to know which version of `polychat-appservice` is running on the server.

- Show version on website https://join.polychat.de/
- `!version` as command in sub rooms

**Comment by yncyrydybyl** [comment]
As long there are no releases it should use the commit hash from the git.

**Comment by yncyrydybyl** [comment]
@lukeelten is going to get the sha into the docker and handing it to @jaller94 to create the appservice command.
